name: HatPuterCppTeaching-CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt (Linux)
        if: runner.os == 'Linux'
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'

      - name: Install Qt (Windows / MinGW)
        if: runner.os == 'Windows'
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: win64_mingw81
          tools: tools_mingw
          aqtversion: '>=3.1.0'
          cache: false

      - name: Install Qt (macOS)
        if: runner.os == 'macOS'
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          qmake HatPuterCppTeaching.pro CONFIG += release
          make

      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: |
          qmake HatPuterCppTeaching.pro CONFIG += release
          sed -i '' 's/-framework AGL//g' Makefile
          make

      - name: Build (Windows / MinGW)
        if: runner.os == 'Windows'
        run: |
          qmake HatPuterCppTeaching.pro CONFIG += release
          mingw32-make
          